{%- extends 'hide.tpl' -%}{% block body %}---
{% for key in resources %}
    {%- if key not in ["metadata", "output_extension", "inlining", "raw_mimetypes", "global_content_filter"] -%}
        {%- if resources[key] != "" -%}
            {{ key }}: {{ resources[key] }}
        {%- endif -%}
    {% endif %}
{% endfor %}
---

<!--

#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: {{ resources.nb_path }}

-->

<div class="container" id="notebook-container">
    {{ super()  }}
</div>
{%- endblock body %}
